### ISSUE TITLE
System.NullReferenceException when send /read or /set

### ISSUE THREAD

**Issue by sascha-egerer** [Hunv/can2mqtt#19]
I do always get a NullReferenceException when trying to read a value.
I've tested version 4.1 - 4.3

```
CONNECTION TO MQTT BROKER 192.168.1.123 established using ClientId Can2Mqtt
CONNECTED TO SOCKETCAND 192.168.1.124 ON PORT 29536
Handshake successful. Opening CAN interface...
Opening connection to slcan0 successful. Changing socketcand mode to raw...
Change to rawmode successful
Received MQTT READ Message; Topic = heating/room/hc1/temperature/day/read
Already connected to SocketCanD.
Failed to send a read via CAN bus. Error: System.NullReferenceException: Object reference not set to an instance of an object.
   at can2mqtt.Can2Mqtt.ReadCan(String topic, String canServer, Int32 canPort) in C:\Dev\can2mqtt\can2mqtt_core\can2mqtt_core\can2mqtt.cs:line 277
```

**Comment by Hunv** [comment]
Hi @sascha-egerer ,
Does socketcand works correctly?
I.e. dies this step from the instruction work?
`/opt/socketcand/socketcand -i slcan0 -l eth0 -v`

**Comment by sascha-egerer** [comment]
Yes, the issue is if the application is started and the first command is a send

**Comment by Hunv** [comment]
OK, try the latest update I just released (v4.4)

**Comment by Oldscrewdriver** [comment]
I get now:

`dotnet /opt/can2mqtt/can2mqtt.dll
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at can2mqtt.Can2Mqtt.LoadConfig() in D:\Productions\#git\can2mqtt\can2mqtt_core\can2mqtt_core\can2mqtt.cs:line 81
   at can2mqtt.Can2Mqtt.StartAsync(CancellationToken stoppingToken) in D:\Productions\#git\can2mqtt\can2mqtt_core\can2mqtt_core\can2mqtt.cs:line 105
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Program.<Main>$(String[] args) in D:\Productions\#git\can2mqtt\can2mqtt_core\can2mqtt_core\Program.cs:line 12
   at Program.<Main>(String[] args)
`

with a config.jason:

`{^M
  "CanForwardRead": false,^M
  "CanForwardResponse": true,^M
  "CanReceiveBufferSize": 48,^M
  "CanSenderId": "69F",^M
  "CanInterfaceName":"can0",
^M
  "MqttServer": "192.168.2.160",^M
  "MqttClientId": "Can2Mqtt",^M
  "MqttTopic": "heating",^M
  "MqttTranslator": "StiebelEltron",^M
  "MqttUser": "home_assistant",^M
  "MqttPassword": "xxxxxxxxxx",^M
  "MqttAcceptSet": false,^M
^M
  "NoUnits": false,^M
  "Language": "en"^M
}^M
`

**Comment by Hunv** [comment]
`D:\Productions\#git\can2mqtt\can2mqtt_core\can2mqtt_core\can2mqtt.cs:line 81` is the line where the config is loaded. In Detail the `MqttTranslator` setting. Are you sure you are using the latest version? I ask as the next line (105) refers to a comment and not a line with code.

**Comment by sascha-egerer** [comment]
@Hunv Thank you for your feedback. I was not able to test it as the SD Card in my raspberry pi, that has been used, died...

**Comment by Hunv** [comment]
No further feedback
